# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-24 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dating_location',
            field=models.CharField(choices=[('北京', '北京'), ('上海', '上海'), ('深圳', '深圳'), ('武汉', '武汉'), ('成都', '成都'), ('西安', '西安'), ('沈阳', '沈阳')], default='上海', max_length=10, verbose_name='目标城市'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(choices=[('北京', '北京'), ('上海', '上海'), ('深圳', '深圳'), ('武汉', '武汉'), ('成都', '成都'), ('西安', '西安'), ('沈阳', '沈阳')], default='上海', max_length=10, verbose_name='常居地'),
        ),
    ]
